### PR TITLE
graph: bugfix for initializer

### LINKED ISSUE #147: Error: load converted models keras2onnx
Error: invalid name for initializer: W when load model
this first conv layer in model

### PR DESCRIPTION
**Pull request by fs-eire**
- allows implicit inputs in initializers
- allows inputs with multiple None dimensions

Fixes #147

### CODE REVIEW

File: lib/session.ts [hunk 1]
```diff
@@ -203,23 +203,10 @@ export class Session {
...
-          if (noneDimSeen) {
-            return false;
-          }
-
-          noneDimSeen = true;
-        }
-
-        // Not a 'None' dimension. Data shape mis-match.
-        else {
+        if (!noneDimSupported || expectedDims[i] !== 0) {
```
Comment (hariharans29) [inline lib/session.ts]: maybe just merge the 2 ifs  expectedDims[i] !== actualDims[i] && (... || ...) ?
